[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/api/Dockerfile"

[deploy]
startCommand = "npx prisma migrate deploy --schema=packages/database/prisma/schema.prisma && node dist/main"
restartPolicyType = "ON_FAILURE"
